### ISSUE TITLE
require 'ons' loaderror

### ISSUE THREAD

**Issue by Go-Faram** [souche/aliyun-ons-ruby-sdk#1]
```
:002 > require 'ons'
LoadError: /home/code/.rvm/gems/ruby-2.3.1@mq/gems/ons-1.0.1/lib/ons/ons.so: undefined symbol: _ZN3ons18ONSFactoryProperty9AccessKeyB5cxx11E - /home/code/.rvm/gems/ruby-2.3.1@mq/gems/ons-1.0.1/lib/ons/ons.so
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/ons-1.0.1/lib/ons.rb:4:in `require'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/ons-1.0.1/lib/ons.rb:4:in `<top (required)>'
	from (irb):2:in `require'
	from (irb):2
	from /home/code/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<top (required)>'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/bin/bundle:23:in `load'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/bin/bundle:23:in `<main>'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/bin/ruby_executable_hooks:15:in `eval'
	from /home/code/.rvm/gems/ruby-2.3.1@mq/bin/ruby_executable_hooks:15:in `<main>'

```
这个怎么解决哟,系统是ubuntu 16.04

**Comment by ghost** [comment]
Ubuntu 16.04 自带的 GCC5.4 默认采用的 ABI 与 GCC4 系列不一致导致的。

----

按照下面步骤重新安装：

```bash
$ gem uninstall rice
$ gem uninstall ons
$ CPPFLAGS='-D_GLIBCXX_USE_CXX11_ABI=0' gem install rice
$ CPPFLAGS='-D_GLIBCXX_USE_CXX11_ABI=0' gem install ons
```
